### ISSUE TITLE
[BE] 공유 이미지 업로드 구현

### ISSUE THREAD

**Issue by ejm111333** [boostcampwm-2024/web11-boostproject#123]
# Task 요약
> 클라이언트로부터 이미지 버퍼를받아 개발, 배포 환경에 따라 이미지를 업로드 후 url 반환합니다.

# 세부 설명
- **핵심 목표**: 환경에 따라 이미지 업로드 방식을 다르게 합니다.
- **요구사항 및 조건**:
  - [x] 이미지 버퍼를 받아 오브젝트 스토리에 올려 url 반환
  - [x] 이미지 버퍼를 프로젝트 로컬 에 생성하여 url 반환
  - [x] `repository` 에 개발, 배포 환경을 구분하여 각각 맞는 의존성 주입

# 고민과 해결
## 오브젝트 스토리지 업로드
- `aws-sdk`로 `ncp` 오브젝트 스토리지에 접근이 가능하여 클라이언트에 받은 이미지 버퍼를 오브젝트 스토리지에 접근하여 업로드하여 해당 이미지 URL을 반환
- 업로드시 `ACL: 'public-read'` 으로 지정해줘야 업로드후 이미지 접근이 가능함
    ```typescript
    private s3: AWS.S3;
    
      private endpoint: AWS.Endpoint;
      private region: string;
      private access_key: string;
      private secret_key: string;
    
      constructor(private configService: ConfigService) {
        this.endpoint = new AWS.Endpoint(this.configService.get<string>('ENDPOINT'));
        this.region = this.configService.get<string>('REGION');
        this.access_key = this.configService.get<string>('ACCESS_KEY');
        this.secret_key = this.configService.get<string>('SECRET_KEY');
    
        this.s3 = new AWS.S3({
          endpoint: this.endpoint.href,
          region: this.region,
          credentials: {
            accessKeyId: this.access_key,
            secretAccessKey: this.secret_key,
          },
        });
      }

     ////////////////////////////

     async uploadImage(data: InterestsImageDto) {
        const extension = data.fileName.split('.').pop()?.toUpperCase();
        const uniqueFileName = `${uuid()}-${data.fileName}`;
    
        const params = {
          Bucket: 'road-to-friendly-bucket',
          Key: `shareImage/${uniqueFileName}`,
          Body: data.buffer,
          ContentType: ContentTypes[extension],
          ACL: 'public-read',
        };
    
        const result = await this.s3.upload(params).promise();
    
        return result.Location;
      }
    ```
## 이미지 업로드 개발, 배포 환경 분리
- 배포 환경에선 오브젝트 스토리지업로드, 개발 환경에선 프로젝트 로컬 경로에 저장하는 것을 분리해주기 위해서 `repository` 인터페이스로 추상화하여 환경에따라 다른 `repository`를 의존성 주입을 해주었음
  - 인터페이스
     ```typescript
        export interface InterestsRepository {
          addInterestIfBroadcasting(roomId: string, interest: Interest);
          next(roomId: string, hostFlag: boolean, clientId: string);
          deleteRoomInterest(roomId: string);
          uploadImage(data: InterestsImageDto);
        }
     ```
  - `provider`: `INTERESTS_REPOSITORY`라는 토큰을 사용하여 `InterestsRepository`의 구현체를 주입
     ```typescript
      export const InterestsRepositoryProvider: Provider = {
        provide: 'INTERESTS_REPOSITORY',
        useFactory: (configService: ConfigService) => {
          const environment = configService.get<string>('NODE_ENV', 'dev');
      
          if (environment === 'release') {
            return new InterestsImageRepository(configService);
          }
          return new InterestsInMemoryRepository();
        },
        inject: [ConfigService],
      };
      ```
- 서비스에서 `@inject`데코레이터를 사용하여 인터페이스에 의존성 주입
  ```typescript
   constructor(
      @Inject('INTERESTS_REPOSITORY')
      private readonly interestsRepository: InterestsRepository,
    ) {}
  ```
## 개발 환경 이미지 제공
- 이미지 업로드 : 로컬 프로젝트 파일 내에 폴더를 생성하여 이미지를 저장후 해당 url 제공
     ```typescript
            async uploadImage(data: InterestsImageDto) {
                const uniqueFileName = `${uuid()}-${data.fileName}`;
              
                const dirPath = join(__dirname, '..', 'shareImage');
                const filePath = join(dirPath, uniqueFileName);
              
                try {
                  await fs.mkdir(dirPath, { recursive: true });
              
                  await fs.writeFile(filePath, data.buffer);
              
                  return `http://localhost:8080/shareImage/${uniqueFileName}`;
                } catch (error) {
                  throw new Error(error);
                }
              }
    ```
- `ServeStaticModule` : 정적파일을 제공하기위해 설정 `/shareImage/파일명`로 이미지 접근 가능하게함
    ```typescript
        // AppModule
         ServeStaticModule.forRoot({
              rootPath: join(process.cwd(), 'backend', 'interests', 'shareImage'),
              serveRoot: '/shareImage',
            }),

```

# 📌 이슈 사항
- 개발, 배포 분리된 `repository`에서 실질적으로 분리되어서 사용하는건 이미지 업로드 부분이라 나머지 메서드들은 동일하게 작성함
