### ISSUE TITLE
[FE] 공유 리소스가 유튜브인 경우, 공유자만 영상 흐름을 조작할 수 있도록 커스텀한다

### ISSUE THREAD

**Issue by 23YUJIN** [boostcampwm-2024/web11-boostproject#139]
# Task 요약
> 동기화를 위해 공유자에게만 권한 부여

# 세부 설명
- **핵심 목표**: 영상 흐름 조작 권한을 자율적으로 부여하면 일관된 사용자 경험을 보장하기 어려울 수 있으므로, 권한을 공유자에게만 부여한다.
- **요구사항 및 조건**:
  - [x] 공유자는 유튜브 리소스를 재생, 일시중지, 타임라인 변경할 수 있다.
  - [x] 공유자를 제외한 사용자들은 유튜브 리소스 흐름을 제어할 수 없다.
  - [x] 일반적인 유튜브 플레이어로는 권한 부여가 불가능하므로, 플레이어를 커스텀한다. 재생, 일시중지, 타임라인 변경, 프로그래스 바, 볼륨 조절, 재생 속도 변경 등의 플레이어 기능을 제공해야 한다.
    - [x] 공유자에게만 재생, 일시중지 버튼이 보여야 한다. 또한 미디어 영역와 프로그래스바를 포함해 클릭을 통한 흐름 제어는 공유자만 가능해야 한다. 재생 속도 조절도 공유자만이 가능해야 한다.

# 고민과 해결
### 권한을 부여하는 방법에 대한 고민
- iframe 내부는 독립적인 브라우징 컨텍스트를 갖기 때문에, 내부 DOM에 접근할 수 없습니다. postMessage를 통해서만 접근할 수 있는데, 이를 통해 구현된 통로인 유튜브 API에선 권한에 따라 플레이러를 커스텀하는 기능은 제공하지 않습니다. 그러므로 기존 유튜브 플레이어를 사용해선 기존 기능을 구현하기 어렵습니다.
- 컨트롤러를 비활성화하는 옵션은 API에 주어지기 때문에, 컨트롤러를 비활성화 한 뒤, 해당 iframe을 pointer-event:none으로 설정해 클릭 이벤트를 차단하고, 그 위에 커스텀 플레이어로 덮어씌워 권한부여를 구현하기로 하였습니다. 이 과정에서 예상보다 많은 시간이 소요되었습니다.

# 관련 문서 및 참고 링크
> Task에 참고할 수 있는 문서나 링크가 있다면 여기에 추가합니다.

- [참고 링크 1](URL)
- [관련 문서](URL)

# 비고
> Task와 관련하여 추가로 남기고 싶은 설명이나 메모를 작성합니다.
