### ISSUE TITLE
[FE] 질문과 키워드 입력란을 화면에 표시한다

### ISSUE THREAD

**Issue by minsuhan1** [boostcampwm-2024/web11-boostproject#18]
# Task 요약
> 질문을 화면 중앙에 표시하고, 애니메이션을 통해 질문과 입력란을 강조한다. 

# 세부 설명
- **핵심 목표**: Task의 핵심 목표나 기대 효과를 간결하게 설명합니다.
- **요구사항 및 조건**:
  - [ ]  방장을 포함한 모든 참여자들의 화면에 질문 주제가 표시된다
  - [ ]  처음에는 질문이 화면 중앙에 페이드인으로 표시된다.
  - [ ]  1초 뒤에 질문이 위로 살짝 올라가고, 질문이 있던 자리에 키워드 입력란이 생기는 애니메이션을 구현한다

# 고민과 해결
### 해결 방법을 작성합니다.

# 관련 문서 및 참고 링크
> Task에 참고할 수 있는 문서나 링크가 있다면 여기에 추가합니다.

- [참고 링크 1](URL)
- [관련 문서](URL)

# 비고
> Task와 관련하여 추가로 남기고 싶은 설명이나 메모를 작성합니다.
