### ISSUE TITLE
[FE] 키워드가 동적으로 추가되면서 애니메이션이 적용된다

### ISSUE THREAD

**Issue by minsuhan1** [boostcampwm-2024/web11-boostproject#23]
# Task 요약
- 동적으로 화면에 추가되는 키워드들이 서로 겹치지 않으면서 중앙으로 몰리게 배치하는 계산 로직을 구현한다

![슬라이도 애니메이션.gif](https://prod-files-secure.s3.us-west-2.amazonaws.com/46c28fc4-60c6-4766-8b45-e86973ff45e5/f79c3029-85c4-4ca1-b32b-1d75136c396d/%EC%8A%AC%EB%9D%BC%EC%9D%B4%EB%8F%84_%EC%95%A0%EB%8B%88%EB%A9%94%EC%9D%B4%EC%85%98.gif)

# 세부 설명
- **핵심 목표**: Task의 핵심 목표나 기대 효과를 간결하게 설명합니다.
- **요구사항 및 조건**:
  - [ ]  실시간 키워드들이 동적 애니메이션과 함께 추가 된다.
  - [ ]  겹치지 않으면서도 중앙부터 배치하는 로직으로 구현한다.
     - [ ]  이미 존재하는 위치에 생성될 경우, 기존에 존재하는 요소를 밀어내는 애니메이션을 추가한다.
     - [ ]  상위 키워드일수록 중앙에 위치해야 한다
     - [ ]  중앙으로 이동하는 과정에서 애니메이션을 적용한다
  - [ ]  새로 추가되는 키워드는 scale-up/zoom-in 애니메이션(작았다가 커지는)을 적용한다.
  - [ ]  최대 키워드 수 설정 → 넘어가면 하위 키워드 중 하나를 랜덤으로 삭제
    
    ![많으면사라짐.gif](https://prod-files-secure.s3.us-west-2.amazonaws.com/46c28fc4-60c6-4766-8b45-e86973ff45e5/58e840e9-47cb-452e-91ee-d4ce9bb081d3/%EB%A7%8E%EC%9C%BC%EB%A9%B4%EC%82%AC%EB%9D%BC%EC%A7%90.gif)
    
    ![커지는거.gif](https://prod-files-secure.s3.us-west-2.amazonaws.com/46c28fc4-60c6-4766-8b45-e86973ff45e5/0e08cb16-c78e-4688-b57e-25fee4ee6c7b/%EC%BB%A4%EC%A7%80%EB%8A%94%EA%B1%B0.gif)

# 고민과 해결
### 해결 방법을 작성합니다.

# 관련 문서 및 참고 링크
> Task에 참고할 수 있는 문서나 링크가 있다면 여기에 추가합니다.

- [참고 링크 1](URL)
- [관련 문서](URL)

# 비고
- 최대 몇일까지 도전해봐야할까…?
- 어려워 보이는 코어로직 → 페어 프로그래밍도 고려해보기
- 스케일 줄이기는 도전과제!!
