### ISSUE TITLE
[FE] 서버가 전달한 질문 리스트 중 마지막 질문의 타임스탬프에 기록된 시간이 되면 전환 페이지를 띄우고 서버에게 종료 알림을 전송한다

### ISSUE THREAD

**Issue by minsuhan1** [boostcampwm-2024/web11-boostproject#29]
# Task 요약
- 서버가 전달한 질문 리스트 중 마지막 질문의 만료 timestamp 시간에 도달하면 강제적으로 전환 페이지(’ex. 공감포인트 나누기가 끝났어요. 분석하고 있어요~’)를 띄운다.
- 서버가 종료 통계를 취합할 수 있도록 알림을 전송한다.

# 세부 설명
- **핵심 목표**: Task의 핵심 목표나 기대 효과를 간결하게 설명합니다.
- **요구사항 및 조건**:
  - [x]  중간 페이지를 띄운다.
  - [ ]  종료 알림을 서버에게 보낸다.
  - [x]  중간 페이지의 내용은 “공감 포인트 모으기가 끝났어요. 조금만 기다리시면 통계를 확인하거나 컨텐츠를 공유할 수 있어요.”이다. 해당 페이지는 나타날 때 페이드인으로 나타난다.
  - [ ]  서버에서 자체 조건에 맞게 종료를 인지하고 데이터를 보내면 중간 페이지 디스플레이를 종료한다.

# 고민과 해결
### 해결 방법을 작성합니다.

# 관련 문서 및 참고 링크
> Task에 참고할 수 있는 문서나 링크가 있다면 여기에 추가합니다.

- [참고 링크 1](URL)
- [관련 문서](URL)

# 비고
> Task와 관련하여 추가로 남기고 싶은 설명이나 메모를 작성합니다.
