### ISSUE TITLE
[FE] 참여자별 상위 N개 키워드를 화면에 표시한다

### ISSUE THREAD

**Issue by minsuhan1** [boostcampwm-2024/web11-boostproject#31]
# Task 요약
전체 질문에 대한 각자 답변들 중 공감을 많이 받은 상위 N개를 필터링해서 표시

# 세부 설명
- **핵심 목표**: Task의 핵심 목표나 기대 효과를 간결하게 설명합니다.
- **요구사항 및 조건**:
  - [ ]  키워드의 인기도는 그대로 유지된다
  - [ ]  (답변 입력 때와는 달리) 인기도를 크기로 구분할 수 없으므로 main color의 채도 등으로 구분할 수 있게 한다
  - [ ]  키워드는 답변 입력할때와 달리 inactive 상태이다 (선택 또는 선택취소 불가)

# 고민과 해결
### 해결 방법을 작성합니다.

# 관련 문서 및 참고 링크
> Task에 참고할 수 있는 문서나 링크가 있다면 여기에 추가합니다.

- [참고 링크 1](URL)
- [관련 문서](URL)

# 비고
> Task와 관련하여 추가로 남기고 싶은 설명이나 메모를 작성합니다.
