### ISSUE TITLE
[BE] FE CI/CD 파이프라인을 설정한다

### ISSUE THREAD

**Issue by eora21** [boostcampwm-2024/web11-boostproject#58]
# Task 요약
> FE가 merge되었을 때 난독화 빌드 파일을 object storage에 업로드하고 이를 최신화합니다.

# 세부 설명
- **핵심 목표**: FE의 빌드 파일 배포를 자동화합니다.
- **요구사항 및 조건**:
  - [ ] github actions을 사용하여 FE의 정상 merge를 확인합니다.
  - [ ] React의 build (+ 난독화) 파일을 생성합니다.
  - [ ] build 파일을 object storage에 업로드합니다.
  - [ ] 업로드된 파일을 인스턴스에 적용합니다.

# 고민과 해결
### 해결 방법을 작성합니다.

# 관련 문서 및 참고 링크
> Task에 참고할 수 있는 문서나 링크가 있다면 여기에 추가합니다.

- [참고 링크 1](URL)
- [관련 문서](URL)

# 비고
> Task와 관련하여 추가로 남기고 싶은 설명이나 메모를 작성합니다.
