### ISSUE TITLE
[BE] BE CI/CD 파이프라인을 설정한다

### ISSUE THREAD

**Issue by eora21** [boostcampwm-2024/web11-boostproject#59]
# Task 요약
>BE CI/CD 파이프라인을 설정합니다.

# 세부 설명
- **핵심 목표**: BE 자동 배포를 구성합니다.
- **요구사항 및 조건**:
  - [x] BE 코드의 정상 merge를 확인합니다.
  - [x] github actions에서 build 파일을 생성합니다.
  - [x] 서버로 build 파일을 이동시킵니다.
  - [x] 해당 파일을 pm2로 실행합니다.

# 고민과 해결
### 인메모리 방식으로 인한 기존 서버와 새 서버 간 불통
현재는 로직이 인메모리를 사용하고 있기 때문에, graceful shutdown을 도입해도 문제가 생깁니다. 이전 버전의 서버와 다음 버전의 서버가 소통할 수 없기 때문입니다.

### redis 이용
redis를 이용하여 소켓 연결 및 방의 정보들을 유지하고, 서버가 달라도 접속할 수 있도록 구성할 계획입니다.
### 방 재입장 시
방 재입장 시, 해당 방의 정보를 FE에 재공해야 '어떤 데이터들을 주고받았는가'를 알 수 있습니다.

그러나 FE 코드가 현재 소켓 이벤트를 기반으로 데이터를 구성하기 때문에, 추후 리팩터링 전까지는 '준비 상태가 아닌 방은 입장 불가' 로직을 구성해야 할 듯 합니다.

# 관련 문서 및 참고 링크
https://velog.io/@mw310/NginxSpring-Boot-%EB%AC%B4%EC%A4%91%EB%8B%A8-%EB%B0%B0%ED%8F%AC-%EA%B5%AC%EC%B6%95%ED%95%98%EA%B8%B0

https://inpa.tistory.com/entry/node-%F0%9F%93%9A-PM2-%EB%AA%A8%EB%93%88-%EC%82%AC%EC%9A%A9%EB%B2%95-%ED%81%B4%EB%9F%AC%EC%8A%A4%ED%84%B0-%EB%AC%B4%EC%A4%91%EB%8B%A8-%EC%84%9C%EB%B9%84%EC%8A%A4

https://pm2.keymetrics.io/docs/usage/signals-clean-restart/

https://pm2.keymetrics.io/docs/tutorials/pm2-nginx-production-setup

https://velog.io/@chltjdrhd777/%EC%9E%90%EB%8F%99%ED%99%94-%EA%B0%9C%EB%B0%9C-%ED%9A%8C%EA%B3%A0-EC2-PM2-Nginx-%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EB%AC%B4%EC%A4%91%EB%8B%A8-%EB%B0%B0%ED%8F%AC-%EA%B5%AC%EC%B6%95%EA%B8%B0

https://blog.naver.com/gi_balja/223037996328

https://www.ryuollojy.com/articles/nodejs-graceful-shutdown

https://blog.rhostem.com/posts/2019-10-23-pm2-graceful-reload

https://engineering.linecorp.com/ko/blog/pm2-nodejs

https://stackoverflow.com/questions/59268098/is-it-possible-to-deploy-without-downtime-without-disconnecting-tcp-sockets-conn
# 비고
서버 리팩터링이 필요합니다.
