### ISSUE TITLE
[BE] 모든 키워드 입력이 종료될 시 자동으로 통계 내용을 전달한다

### ISSUE THREAD

**Issue by eora21** [boostcampwm-2024/web11-boostproject#66]
# Task 요약
> 서버에서 자동으로 통계 내용을 전달합니다.

# 세부 설명
- **핵심 목표**: 종료 시간에 맞춰 키워드 통계 데이터를 자동으로 전달합니다.
- **요구사항 및 조건**:
  - [x] 서버는 각 방의 키워드 입력 종료 시간을 인지하고 있어야 합니다.
  - [x] 해당 시간이 되었을 경우 자동으로 통계 데이터를 전달합니다.
  - [ ] 부가 목표
    - [ ] 참가자들의 시간 연장, 단축에 대해 확장성을 지녀야 합니다.
    - [ ] 네트워크 전달 시간까지 고려해야 합니다.

# 고민과 해결
## 시간 연장, 단축에 대해 어떻게 처리할 것인가
서버가 각 방의 최종 종료 시간을 알고 있다 하더라도, 이는 변동될 수 있습니다. 따라서 timeout같은 방법이 아닌 다른 방법을 고려해봐야 합니다.

### 클라이언트의 종료 이벤트 수신
모든 참여자의 과반수에 대해 종료 이벤트가 수신될 경우 통계를 도출하고 전달합니다. 서버에서 따로 이벤트를 관리할 필요가 없으며, 해당 방의 종료 시그널이 과반수 이상인지만 파악하면 되기에 효율적입니다.

### job으로 이벤트 등록, 시간 변경 시 재설정
방마다 종료 시간에 이벤트를 걸어두고, 만약 시간이 변동된다면 재설정하도록 합니다. 이는 클라이언트 및 서버의 네트워크 환경과 무관하게 진행됩니다.

### redis의 key expire event 사용
redis에 해당 방 이름으로 된 key를 입력하고, 종료 시간에 대해 TTL을 적용합니다.

클라이언트의 시간 증가, 감소 등은 TTL 변경으로 대처합니다.

추후 키가 만료되는 경우 key expire event를 수신할 수 있습니다.

## MVP에서는 setTimeout으로 간단하게
MVP만 따질 경우, 시간 연장과 단축은 고려되지 않습니다.
빠른 개발을 위해 setTimeout으로 구성하기로 했습니다.

# 관련 문서 및 참고 링크

# 비고
