### ISSUE TITLE
[BE] Empathy 도메인을 Keywords 도메인으로 리팩터링한다

### ISSUE THREAD

**Issue by eora21** [boostcampwm-2024/web11-boostproject#67]
# Task 요약
> 의미가 명확하지 않은 Empathy 도메인을 Keywords 도메인으로 리팩터링합니다.

# 세부 설명
- **핵심 목표**: 클라이언트의 키워드 입력에 대해 통계 및 이벤트를 최적화합니다.
- **요구사항 및 조건**:
  - [x] 도메인명 변경
  - [x] 키워드 저장소 리팩터링
    - [x] 주제 id와 키워드 합쳐서 관리
    - [x] 통계 생성 알고리즘 간략화
    - [x] 추가적인 요청에 대해 생성한 통계를 전달

# 고민과 해결
## 시간복잡도를 줄일 수 있는 방법은 없는가
정렬을 클라이언트에서 수행하는 방법을 제외하고는 특별히 최적화가 이뤄지긴 힘들 것 같습니다.

O(nlogn + n * m)형태이기에, 참여자 수와 키워드 수가 극도로 많아진다면 어떻게 해야 할 지 감이 잘 오지 않습니다.

워커 스레드를 통한 Serialization 분산이 최대인가? 라는 생각이 듭니다.

# 관련 문서 및 참고 링크

# 비고
## 구조 그림
![Image](https://github.com/user-attachments/assets/01df5a31-7767-460c-82d9-72474f747ab3)

## 이후 고민할 부분
- status 통일화
  - status를 `ok`, `error`처럼 응답 상태로 두고 `pick`, `release`같은 사용자 이벤트에 따른 값은 따로 기입하는 게 좋을 듯 합니다. action 등.. 좋은 명칭을 떠올려봐야 할 것 같습니다.
