### ISSUE TITLE
[BE] 방 개설을 효율적으로 구성하기 위한 nest와 socket.io를 학습한다

### ISSUE THREAD

**Issue by eora21** [boostcampwm-2024/web11-boostproject#69]
# Task 요약
> 앞으로의 BE 구성을 효율적으로 하기 위해, nest와 socket.io를 학습합니다.

# 세부 설명
- **핵심 목표**: 오픈소스를 살펴보고 현재 프로젝트를 어떤 방향으로 리팩터링할지 생각
- **요구사항 및 조건**:
  - [x] Gateway가 어떻게 동작하는지 살펴봅니다.
    - [x] nest 오픈소스를 살펴봅니다.
    - [x] socket.io 오픈소스를 살펴봅니다.
  - [x] 어떻게 구조를 작성해야 프로젝트가 더 나은 방향성을 지닐 지 고민합니다.

# 고민과 해결
### Adapter의 'Room'은 단순 string
Adapter의 'Room'은 string으로 타입이 잡혀 있습니다. 해당 Room과 프로젝트의 '방' 개념을 일치화하기 위해서는 Adapter를 재정의하거나, Proxy로 감싸야 할 것 같다는 생각이 들었습니다.
### Adapter가 우리 프로젝트의 'Room'을 추상화한다고 생각을 전환하자
코드를 살펴보고 생각을 나누다 보니, 우리의 'Room' 정보를 관리하는 Injectable을 두는 게 좋겠다는 판단을 내렸습니다.

특정 방을 pub하는 것은 방 이름만으로도 충분합니다. '방 진입은 방의 이름을 통해 관리 및 유지'로 생각을 전환하다면 현재의 Adapter로도 이를 만족할 수 있습니다.

따라서 해당 방식으로 사고를 전환하였고, Room이 Interface가 아닌 Type인 이유를 유추할 수 있었습니다.

# 관련 문서 및 참고 링크
- [nest Gateway](https://docs.nestjs.com/websockets/gateways)
- [socket.io](https://socket.io/)
- [nest의 @WebSocketGateway에서 예외 throw 시 클라이언트 콜백으로 응답 전달하기](https://velog.io/@eora21/nest%EC%9D%98-WebSocketGateway%EC%97%90%EC%84%9C-%EC%98%88%EC%99%B8-throw-%EC%8B%9C-%ED%81%B4%EB%9D%BC%EC%9D%B4%EC%96%B8%ED%8A%B8-%EC%BD%9C%EB%B0%B1%EC%9C%BC%EB%A1%9C-%EC%9D%91%EB%8B%B5-%EC%A0%84%EB%8B%AC%ED%95%98%EA%B8%B0)

# 비고
오픈소스를 살펴보며 여러 지식을 얻을 수 있었습니다.
