### ISSUE TITLE
[BE] Rooms 도메인을 리팩터링한다.

### ISSUE THREAD

**Issue by ejm111333** [boostcampwm-2024/web11-boostproject#77]
# Task 요약
> 이 Task의 주요 목적과 내용을 간단히 요약합니다.

# 세부 설명
- **핵심 목표**: Task의 핵심 목표나 기대 효과를 간결하게 설명합니다.
- **요구사항 및 조건**:
  - [x] RoomsRepository 구성
  - [x] 방 메타데이터 삭제 처리
  - [x] service가 아닌 gateway 에서 client socket처리하도록 변경
  - [x] rooms 에서 참여자부분은 clients 로 분리
  - [x] filter, guard 추가
  - [x] 테스트코드 작성

# 고민과 해결
- `RoomsRepository ` 에서 `room`에 대한 정보를 인터페이스로 정의하였고 `room`에대한 페이즈는 `enum`으로 지정하였습니다. 추후에 구조는 변경될 수 있습니다.
    ``` 
    export enum RoomPhase {
      WAITING = 1,
      IN_PROGRESS = 2,
      COMPLETED = 3,
    }
    
    interface Room {
      roomId: string;
      phase: RoomPhase;
      hostId: string;
    }
    ```
- 방에 대한 메타데이터를 제거하는 부부은 소켓 연결이 끊어질때 실행되는 `handleDisconnect` 에서 처리되는데 추후에 `adapter`에서 방을 나갈때 `leave-room, delete-room`이벤트롤 보내주는게 있어서 그걸 받아서 하는게 더 좋아보이면 변경 될 수 있습니다.
- filter에서 이벤트에 콜백이 존재하면 에러에 대한 내용이 콜백으로 전달되지만 콜백이 존재하지않을땐 일단 error이벤트로 전달하였음 이부분에 대해서 얘기를 니눠봐야 할 것 같습니다.

# 비고
