### ISSUE TITLE
[FE] 처음 방에 들어가면 툴팁을 보여준다.

### ISSUE THREAD

**Issue by minsuhan1** [boostcampwm-2024/web11-boostproject#8]
# Task 요약
> 툴팁을 보여줘 사용자에게 공유하기 버튼을 누르도록 유도하는 것이 목적이다.

# 세부 설명
- **핵심 목표**: 툴팁을 보여준다
- **요구사항 및 조건**:
  - [ ]  처음 입장 시 화면이 살짝 어두워지고 블러처리가 이루어진다.
  - [ ]  플로팅 버튼과 툴팁만 z-layer를 높게 둬 명확히 보이게 한다.
  - [ ]  2초 뒤 툴팁과 화면 효과가 사라지며 종료된다.

# 고민과 해결
### 해결 방법을 작성합니다.

# 관련 문서 및 참고 링크
> Task에 참고할 수 있는 문서나 링크가 있다면 여기에 추가합니다.

- [참고 링크 1](URL)
- [관련 문서](URL)

# 비고
- 종료 조건을 시간으로 할 것인지, 사용자 인터렉션으로 할 것인지
