### ISSUE TITLE
[FE] 컨텐츠 공유 모달 컴포넌트 레이아웃 및 구조를 설계한다.

### ISSUE THREAD

**Issue by awaaaake** [boostcampwm-2024/web11-boostproject#89]
# Task 요약
구조를 설계하는 업무이므로 다같이 가장 먼저 진행한다.

# 세부 설명
- **핵심 목표**: 각자 task를 분업해 진행할 때 병목이 생기지 않도록 기초적인 구조를 미리 작성해두는 걸 목적으로 한다. 
- **요구사항 및 조건**:
- [ ]  컨텐츠 공유 시작하기’ 또는 ‘+’ 버튼을 누르면 어떤 컨텐츠를 공유할지 물어보는 모달을 표시한다.
- [ ]  우상단의 x 버튼을 누르면 모달창을 닫을 수 있다.
- [ ]  특정 공유 방법을 선택했을 경우 돌아가기 버튼이 좌상단에 나타나며, 돌아가기 버튼을 누르면 이전 페이지가 표시된다.
- [ ]  컴포넌트 뼈대(레이아웃 배치, UI적인 상태 분기처리) 작성이 완료되어서 스타일이나 feature 없이 UI를 테스트할 수 있다.

# 고민과 해결
### 해결 방법을 작성합니다.

# 관련 문서 및 참고 링크
> Task에 참고할 수 있는 문서나 링크가 있다면 여기에 추가합니다.

- [참고 링크 1](URL)
- [관련 문서](URL)

# 비고
> Task와 관련하여 추가로 남기고 싶은 설명이나 메모를 작성합니다.
