### ISSUE TITLE
[FE] 유튜브로 전송하기 기능을 구현한다

### ISSUE THREAD

**Issue by awaaaake** [boostcampwm-2024/web11-boostproject#90]
# Task 요약
> 이 Task의 주요 목적과 내용을 간단히 요약합니다.
모달에서 유튜브로 공유하기를 선택할 경우, 주소를 입력할 수 있는 입력 form이 나타나고 제출하기 버튼이 표시된다.

# 세부 설명
- **핵심 목표**: 사용자가 유튜브 링크를 입력할 수 있도록 하고, 입력된 링크 영상 미리보기를 표시해 사용자가 제대로 된 링크를 입력했는지 판단할 수 있도록 한다. 사용자가 제출할 경우 서버로 유튜브 주소를 전송해 알려준다.
- **요구사항 및 조건**:
- [ ]  제출하기 버튼은 주소 입력 form이 채워졌을 때에만 활성화된다.
- [ ]  제출하기 버튼을 누르면 해당 유튜브 주소를 소켓으로 서버에 전송한다.
- [ ]  제출 중 로딩 인디케이터를 표시한다.
- [ ]  form 입력 후 엔터 누르면 유효한 유튜브 링크인지 확인하고, 유효하다면 아래에 미리보기를 표시한다.
    - [ ]  유효하지 않을 경우 toast 메시지를 표시한다
- [ ]  서버로 전송 과정에서 소켓 연결이 불안정할 경우 토스트 메시지를 띄워 안내하고, 입력 form 내용은 그대로 둔다.
- [ ]  서버로 전송이 성공적일 경우 모달창을 닫는다.
- [ ]  서버로 유튜브 주소를 포함해 소켓으로 전송하고, 전송이 성공적일 경우 모달창을 닫는다. 실패할 경우 다시 버튼을 누르도록 한다.

# 고민과 해결
## Task를 진행하며 생겼던 고민 사항을 작성합니다.
- 유효한 유튜브 링크 판별을 API로 가능한지 담당자가 조사 후, 해당 요구사항을 유지하거나 변경할지 결정
### 해결 방법을 작성합니다.

# 관련 문서 및 참고 링크
> Task에 참고할 수 있는 문서나 링크가 있다면 여기에 추가합니다.

- [참고 링크 1](URL)
- [관련 문서](URL)

# 비고
> Task와 관련하여 추가로 남기고 싶은 설명이나 메모를 작성합니다.
