### ISSUE TITLE
[FE] 사진 전송하기 기능을 구현한다.

### ISSUE THREAD

**Issue by awaaaake** [boostcampwm-2024/web11-boostproject#91]
# Task 요약
> 이 Task의 주요 목적과 내용을 간단히 요약합니다.
모달에서 이미지 공유하기를 선택할 경우, 이미지를 업로드할 수 있는 입력 form이 나타나고 제출하기 버튼이 표시된다.

# 세부 설명
- **핵심 목표**: 사용자가 form에서 이미지를 첨부하고, 미리보기로 확인한 다음 제출하여 소켓 서버로 전달한다.
- **요구사항 및 조건**:
- [x]  지원하는 이미지 파일은 jpeg, png
- [x]  이미지 파일 용량 제한은 → 백엔드 협의?
- [x]  이미지는 파일 탐색기, 드래그앤드롭, 클립보드 붙여넣기를 지원한다
- [x]  업로드된 이미지가 존재할 경우에만 입력 form은 이미지 미리보기로 변하며 하단의 제출하기 버튼이 활성화된다.
- [x]  첨부한 이미지를 제거할 수 있어야 한다.
- [x]  제출하기 버튼을 누르면 이미지 제출 이벤트를 소켓으로 서버에 전송한다.
- [x]  제출 중 로딩 인디케이터를 표시한다.
- [x]  서버로 전송 과정에서 소켓 연결이 불안정할 경우 토스트 메시지를 띄워 안내하고, 입력 form 내용은 그대로 둔다.
- [x]  서버로 전송이 성공적일 경우 모달창을 닫는다.
- [x]  서버로 이미지 제출을 소켓으로 전송하고, 전송이 성공적일 경우 모달창을 닫는다. 실패할 경우 다시 버튼을 누르도록 한다.

# 고민과 해결
### 해결 방법을 작성합니다.

# 관련 문서 및 참고 링크
> Task에 참고할 수 있는 문서나 링크가 있다면 여기에 추가합니다.

- [참고 링크 1](URL)
- [관련 문서](URL)

# 비고
> Task와 관련하여 추가로 남기고 싶은 설명이나 메모를 작성합니다.
