### ISSUE TITLE
[FE] 공유 리소스가 유튜브일 경우, 공유자의 흐름 조작은 모든 클라이언트에서 동기화가 되어야 한다.

### ISSUE THREAD

**Issue by awaaaake** [boostcampwm-2024/web11-boostproject#95]
# Task 요약
> 재생/일시중지/타임라인 변경 시 모든 클라이언트에 동기화하기 위해 서버와 소켓 통신을 주고받아야 합니다.

# 세부 설명
- **핵심 목표**: 서버와 소켓 통신을 주고받아 공유자의 흐름 조작을 동기화하기, 사용자들에게 일관된 경험
- **요구사항 및 조건**:
- [x]  공유자가 유튜브 리소스의 흐름을 변경할 경우, 서버로 전송된다.
- [x]  그 외 사용자들은 서버로부터 유튜브 리소스 흐름 변경 이벤트를 브로드캐스트로 수신하며, 같은 흐름으로 보도록 동기화가 되어야 한다.
- [x]  만약 공유자가 드래그를 통해 프로그래스바를 조정 중일 경우, 서버로 이벤트를 전송한다.
- [x]  그 외 사용자들의 환경에선 드래그 이벤트를 받을 경우 영상이 일시중지되고 중앙에 드래그 인디케이터를 띄워 사용자에게 인지시켜야 한다.

# 고민과 해결
### 해결 방법을 작성합니다.

# 관련 문서 및 참고 링크
> Task에 참고할 수 있는 문서나 링크가 있다면 여기에 추가합니다.

- [참고 링크 1](URL)
- [관련 문서](URL)

# 비고
> Task와 관련하여 추가로 남기고 싶은 설명이나 메모를 작성합니다.
